import { router, json, error, requireAuth } from '@appdeploy/sdk';
import { db, storage } from '@appdeploy/sdk';
import { createHash } from 'node:crypto';

type Lot={code:string;species:string;origin:string;weightKg:number;status:string;createdAt:string;ownerId:string};
type Doc={name:string;lotId:string;hash:string;status:string;createdAt:string;ownerId:string;contentPath:string};
type Evidence={lotId:string;hash:string;txid:string|null;status:string;createdAt:string;ownerId:string};
const now=()=>new Date().toISOString(); const sha=(s:string)=>createHash('sha256').update(s,'utf8').digest('hex'); const uid=(ctx:{user?:{userId:string}})=>ctx.user!.userId;
async function owned<T>(table:string,userId:string){const r=await db.list<T>(table,{limit:100});return{items:r.items.filter((x:any)=>x.ownerId===userId)}}
export const handler=router({
'GET /api/_healthcheck':[async()=>json({message:'SeaTrace API healthy',version:'1.0.0'})],
'GET /api/lots':[requireAuth(),async ctx=>json(await owned<Lot>('lots',uid(ctx)))],
'POST /api/lots':[requireAuth(),async ctx=>{const b=ctx.body as Partial<Lot>;if(!b.code||!b.species||!b.origin)return error('code, species and origin are required',400);const[id]=await db.add('lots',[{code:String(b.code).trim(),species:String(b.species),origin:String(b.origin),weightKg:Number(b.weightKg||0),status:'Review',createdAt:now(),ownerId:uid(ctx)}]);if(!id)return error('Unable to create lot',500);await db.add('events',[{ownerId:uid(ctx),lotId:id,type:'LOT_CREATED',createdAt:now(),actor:uid(ctx)}]);return json({id,created:true},201)}],
'GET /api/documents':[requireAuth(),async ctx=>json(await owned<Doc>('documents',uid(ctx)))],
'POST /api/documents':[requireAuth(),async ctx=>{const b=ctx.body as{name?:string;lotId?:string;content?:string};if(!b.name||!b.lotId||!b.content)return error('name, lotId and content are required',400);const h=sha(b.content);const path=`evidence/${uid(ctx)}/${b.lotId}/${h}.txt`;const[ok]=await storage.write([{path,content:b.content,contentType:'text/plain'}]);if(!ok)return error('Unable to store evidence',500);const[id]=await db.add('documents',[{name:b.name,lotId:b.lotId,hash:h,status:'Verified',createdAt:now(),ownerId:uid(ctx),contentPath:path}]);if(!id)return error('Unable to register document',500);await db.add('events',[{ownerId:uid(ctx),lotId:b.lotId,type:'DOCUMENT_HASHED',documentId:id,hash:h,createdAt:now(),actor:uid(ctx)}]);return json({id,hash:h,status:'Verified'},201)}],
'GET /api/evidence':[requireAuth(),async ctx=>json(await owned<Evidence>('evidence',uid(ctx)))],
'POST /api/evidence/anchor':[requireAuth(),async ctx=>{const b=ctx.body as{lotId?:string};if(!b.lotId)return error('lotId required',400);const docs=(await owned<Doc>('documents',uid(ctx))).items.filter((d:any)=>d.lotId===b.lotId);if(!docs.length)return error('No document evidence exists for this lot',409);const manifest=sha(JSON.stringify(docs.map((d:any)=>({hash:d.hash,name:d.name,lotId:d.lotId}))));const[id]=await db.add('evidence',[{lotId:b.lotId,hash:manifest,txid:null,status:'READY_TO_ANCHOR',createdAt:now(),ownerId:uid(ctx)}]);if(!id)return error('Unable to create evidence manifest',500);await db.add('events',[{ownerId:uid(ctx),lotId:b.lotId,type:'EVIDENCE_PREPARED',hash:manifest,createdAt:now(),actor:uid(ctx)}]);return json({id,hash:manifest,txid:null,status:'READY_TO_ANCHOR',message:'Evidence manifest creado. Algorand queda preparado para un anchor backend cuando se configure una clave segura.'},201)}],
'POST /api/audit/run':[requireAuth(),async ctx=>{const id=uid(ctx);const lots=(await owned<Lot>('lots',id)).items;const docs=(await owned<Doc>('documents',id)).items;const failures=lots.filter((l:any)=>!docs.some((d:any)=>d.lotId===l.id)).length;const warnings=docs.filter((d:any)=>!d.hash).length;await db.add('auditRuns',[{ownerId:id,createdAt:now(),failures,warnings,lots:lots.length,documents:docs.length}]);return json({summary:{failures,warnings,lots:lots.length,documents:docs.length},message:'Audit completed'})}]
});
