import './styles.css';
import { auth, api } from '@appdeploy/client';

type Lot = { id: string; code: string; species: string; origin: string; weightKg: number; status: string };
type Doc = { id: string; name: string; lotId: string; hash: string; status: string };
type Evidence = { id: string; lotId: string; hash: string; txid: string | null; status: string };

const nav = ['Dashboard','Lotes','Documentos','Compliance','Auditor','Evidence Vault','Buyer Portal','Audit Room'];
let tab = 'Dashboard'; let user: { email?: string; name?: string } | null = null; let lots: Lot[]=[]; let docs: Doc[]=[]; let evidence: Evidence[]=[]; let busy=false; let notice='';
const app=document.querySelector<HTMLDivElement>('#app')!;
const esc=(v:unknown)=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'})[c]||c);
async function load(){ if(!auth.isSignedIn()){render();return;} try{const [l,d,e]=await Promise.all([api.get('/api/lots'),api.get('/api/documents'),api.get('/api/evidence')]);lots=l.data.items||[];docs=d.data.items||[];evidence=e.data.items||[];}catch{notice='No se pudo cargar el workspace.'} render(); }
async function signIn(){busy=true;render();try{const r=await auth.signIn();user=r.user;notice='Sesión iniciada correctamente.';await load()}catch{notice='No se pudo iniciar sesión. Permití ventanas emergentes e intentá nuevamente.'}finally{busy=false;render()}}
async function signOut(){await auth.signOut();user=null;lots=[];docs=[];evidence=[];notice='Sesión cerrada.';render()}
async function createLot(){const code=(document.querySelector<HTMLInputElement>('#lot-code')?.value||'').trim();const species=document.querySelector<HTMLInputElement>('#lot-species')?.value||'Merluza';const origin=document.querySelector<HTMLInputElement>('#lot-origin')?.value||'Argentina';const weightKg=Number(document.querySelector<HTMLInputElement>('#lot-weight')?.value||0);if(!code){notice='El código del lote es obligatorio.';render();return}busy=true;render();try{await api.post('/api/lots',{code,species,origin,weightKg});notice='Lote creado y registrado en el timeline.';await load()}catch{notice='No se pudo crear el lote.'}finally{busy=false;render()}}
async function createDoc(){const name=(document.querySelector<HTMLInputElement>('#doc-name')?.value||'').trim();const lotId=document.querySelector<HTMLSelectElement>('#doc-lot')?.value||'';const content=document.querySelector<HTMLTextAreaElement>('#doc-content')?.value||'';if(!name||!lotId||!content){notice='Completá documento, lote y contenido.';render();return}busy=true;render();try{const r=await api.post('/api/documents',{name,lotId,content});notice=`Documento registrado. SHA-256: ${r.data.hash}`;await load()}catch{notice='No se pudo registrar el documento.'}finally{busy=false;render()}}
async function anchor(lotId:string){busy=true;render();try{const r=await api.post('/api/evidence/anchor',{lotId});notice=r.data.message;await load()}catch{notice='No se pudo preparar la evidencia.'}finally{busy=false;render()}}
async function audit(){busy=true;render();try{const r=await api.post('/api/audit/run',{});notice=`Auditoría finalizada: ${r.data.summary.failures} faltantes, ${r.data.summary.warnings} advertencias.`}catch{notice='No se pudo ejecutar la auditoría.'}finally{busy=false;render()}}
function table(headers:string[],rows:string[][]){return `<div class="table"><div class="tr th">${headers.map(h=>`<span>${esc(h)}</span>`).join('')}</div>${rows.length?rows.map(r=>`<div class="tr">${r.map(c=>`<span>${c}</span>`).join('')}</div>`).join(''):`<div class="empty">No hay registros todavía.</div>`}</div>`}
function panel(title:string,body:string,action=''){return `<section class="panel"><div class="panelhead"><h2>${title}</h2>${action}</div>${body}</section>`}
function dashboard(){const attention=lots.filter(l=>l.status!=='Complete').length;return `<div class="stats"><div class="card"><b>${lots.length}</b><span>Lotes</span><small>registrados</small></div><div class="card"><b>${docs.length}</b><span>Documentos</span><small>con SHA-256</small></div><div class="card"><b>${evidence.length}</b><span>Evidencias</span><small>auditables</small></div><div class="card"><b>${attention}</b><span>Revisión</span><small>requiere atención</small></div></div><div class="two">${panel('Operación',`<div class="timeline"><div class="row"><i class="ok"></i><b>Captura</b><span>Datos operativos</span><em>OK</em></div><div class="row"><i class="${docs.length?'ok':'warn'}"></i><b>Evidencia</b><span>Documentos verificables</span><em>${docs.length?'OK':'PENDIENTE'}</em></div><div class="row"><i class="${lots.length?'ok':'warn'}"></i><b>Compliance</b><span>Controles operativos</span><em>${lots.length?'OK':'PENDIENTE'}</em></div><div class="row"><i class="${evidence.length?'ok':'warn'}"></i><b>Anchor</b><span>Algorand-ready</span><em>${evidence.length?'OK':'PENDIENTE'}</em></div></div>`,'<button data-action="audit">Ejecutar auditoría</button>')} ${panel('Arquitectura','<div class="arch"><b>Operación</b><span>→</span><b>Evidence Layer</b><span>→</span><b>Algorand</b></div><p class="muted">Los datos operativos permanecen fuera de cadena. SeaTrace prepara manifiestos hash para una futura transacción Algorand sin exponer claves de firma en el navegador.</p>')}</div>`}
function lotsView(){return panel('Nuevo lote','<div class="form"><input id="lot-code" placeholder="Código de lote"><input id="lot-species" value="Merluza" placeholder="Especie"><input id="lot-origin" value="Argentina" placeholder="Origen"><input id="lot-weight" type="number" value="1000" placeholder="Peso kg"><button data-action="create-lot">Crear lote</button></div>')+panel('Lotes registrados',table(['Código','Especie','Origen','Peso','Estado'],lots.map(l=>[esc(l.code),esc(l.species),esc(l.origin),`${l.weightKg} kg`,esc(l.status)])))}
function docsView(){const options=lots.map(l=>`<option value="${esc(l.id)}">${esc(l.code)}</option>`).join('');return panel('Registrar documento','<div class="form"><input id="doc-name" placeholder="Nombre del documento"><select id="doc-lot"><option value="">Seleccioná lote</option>'+options+'</select><textarea id="doc-content">SeaTrace evidence record</textarea><button data-action="create-doc">Calcular hash y registrar</button></div>')+panel('Evidence documents',table(['Documento','Lote','SHA-256','Estado'],docs.map(d=>[esc(d.name),esc(lots.find(l=>l.id===d.lotId)?.code||'—'),esc(d.hash.slice(0,18)+'…'),esc(d.status)])))}
function complianceView(){const rules=[['Identidad del lote',lots.length>0,'Control interno v1.0'],['Evidencia documental',docs.length>0,'Control de expediente v1.0'],['Integridad criptográfica',docs.length>0&&docs.every(d=>!!d.hash),'SHA-256'],['Cadena completa',lots.length>0&&docs.length>=lots.length,'SeaTrace control v1.0']];return panel('Compliance matrix',`<div class="rules">${rules.map(r=>`<div class="rule"><strong class="${r[1]?'green':'amber'}">●</strong><div><b>${r[0]}</b><small>${r[2]}</small></div><em>${r[1]?'COMPLIANT':'REVIEW'}</em></div>`).join('')}</div><p class="muted">Controles operativos de la demo; no constituyen certificación regulatoria ni asesoramiento legal.</p>`)}
function auditorView(){const findings=lots.filter(l=>!docs.some(d=>d.lotId===l.id));return panel('Auditoría',`<button data-action="audit" ${busy?'disabled':''}>Ejecutar revisión completa</button><div class="findings">${findings.length?findings.map(l=>`<div class="finding"><b>⚠ ${esc(l.code)}</b><span>Lote sin evidencia documental</span></div>`).join(''):'<div class="success">✓ No hay faltantes detectados con las reglas activas.</div>'}</div>`)}
function evidenceView(){return panel('Evidence Vault',table(['Lote','Hash','Algorand','Estado','Acción'],evidence.map(e=>[esc(lots.find(l=>l.id===e.lotId)?.code||'—'),esc(e.hash.slice(0,20)+'…'),esc(e.txid||'Pendiente'),esc(e.status),`<button data-anchor="${esc(e.lotId)}" ${busy?'disabled':''}>Anclar</button>`])))}
function buyerView(){return panel('Buyer Portal','<p class="muted">Acceso de comprador sin wallet: verificación independiente del expediente autorizado.</p>'+table(['Lote','Estado','Evidencia','Verificación'],lots.map(l=>[esc(l.code),esc(l.status),evidence.some(e=>e.lotId===l.id)?'Disponible':'Pendiente',`<button data-verify="${esc(l.id)}">Verificar</button>`])))}
function auditRoom(){const manifest={generatedBy:'SeaTrace',lots:lots.map(l=>l.code),evidence:evidence.map(e=>({hash:e.hash,txid:e.txid,status:e.status}))};return panel('Audit Room',`<div class="stats"><div class="card"><b>${lots.length}</b><span>Lotes</span></div><div class="card"><b>${docs.length}</b><span>Docs</span></div><div class="card"><b>${evidence.length}</b><span>Anchors</span></div></div><div class="manifest"><b>Expediente verificable</b><p>Timeline → documentos → hashes → controles → evidencia on-chain.</p><pre>${esc(JSON.stringify(manifest,null,2))}</pre></div>`)}
function currentView(){switch(tab){case'Lotes':return lotsView();case'Documentos':return docsView();case'Compliance':return complianceView();case'Auditor':return auditorView();case'Evidence Vault':return evidenceView();case'Buyer Portal':return buyerView();case'Audit Room':return auditRoom();default:return dashboard()}}
function render(){app.innerHTML=`<header><div class="brand"><span class="mark">S</span><div><strong>SeaTrace</strong><small>Traceability Infrastructure</small></div></div><div class="top"><span class="secure">● Sistema operativo</span>${user?`<span>${esc(user.email||user.name||'Usuario')}</span><button class="ghost" data-action="signout">Salir</button>`:`<button data-action="signin" ${busy?'disabled':''}>Iniciar sesión</button>`}</div></header><div class="layout"><aside><div class="workspace">WORKSPACE<br><b>${user?'Mi organización':'Demo workspace'}</b></div>${nav.map(n=>`<button class="nav ${tab===n?'active':''}" data-tab="${esc(n)}">${esc(n)}</button>`).join('')}<div class="sidefoot">Evidence-first<br>Algorand ready<br><b>by ElCryptoBoy</b></div></aside><main class="content"><div class="crumb">SEATRACE / ${esc(tab.toUpperCase())}</div><div class="title"><div><h1>${esc(tab)}</h1><p>Control de trazabilidad, evidencia y compliance para operaciones pesqueras.</p></div><span class="pill">${lots.length} lotes</span></div>${notice?`<div class="notice">${esc(notice)}</div>`:''}${currentView()}</main></div>`}
document.addEventListener('click',async e=>{const el=e.target as HTMLElement;const tabName=el.closest<HTMLElement>('[data-tab]')?.dataset.tab;if(tabName){tab=tabName;notice='';render();return}const action=el.closest<HTMLElement>('[data-action]')?.dataset.action;if(action==='signin')return signIn();if(action==='signout')return signOut();if(action==='create-lot')return createLot();if(action==='create-doc')return createDoc();if(action==='audit')return audit();const lot=el.closest<HTMLElement>('[data-anchor]')?.dataset.anchor;if(lot)return anchor(lot);const verify=el.closest<HTMLElement>('[data-verify]')?.dataset.verify;if(verify){notice=`Verificación SeaTrace: ${lots.find(l=>l.id===verify)?.code||'lote'} — expediente consultado.`;render()}});
void auth.getUser().then(u=>{user=u;return load()}).catch(()=>render());
